services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CinemaPack\:
    resource: '../../src/'

  CinemaPack\Contracts\CinemaCountryMapperInterface:
    class: 'CinemaPack\Mapper\CinemaCountryMapper'

  CinemaPack\Contracts\CinemaCityMapperInterface:
    class: 'CinemaPack\Mapper\CinemaCityMapper'

  CinemaPack\Contracts\CinemaImageMapperInterface:
    class: 'CinemaPack\Mapper\CinemaImageMapper'

  CinemaPack\Contracts\CinemaNameMapperInterface:
    class: 'CinemaPack\Mapper\CinemaNameMapper'

  CinemaPack\Contracts\CinemaUrlMapperInterface:
    class: 'CinemaPack\Mapper\CinemaUrlMapper'