<?php

namespace CinemaPack\Dto;


use CinemaPack\Enum\CinemaIdEnum;
use CountryPack\Dto\CountryDto;

class CinemaDto
{
    public function __construct(
        public CinemaIdEnum $id,
        public CountryDto   $country,
        public string       $name,
        public ?string      $url,
        public ?string      $imageUrl,
        /**
         * @var string[] The list of cities where this cinema operates.
         *
         * @note The initial data for this property was generated by an AI model gemini-2.5-pro
         * on 2025-10-11 and should be reviewed for accuracy.
         */
        public array        $cities = [],
    )
    {
    }
}